Issue 38 replace deprecated bower
lluiscampos/trevaling pull request #40
Opened 2017-06-19 22:20 UTC by cristiantrave

First steps for webpack implementation in rosetta. Removed bower. Now the libraries are managed by npm.

2017-06-20 07:12 UTC, lluiscampos requested changes
See my comments

2017-06-20 07:12 UTC, lluiscampos commented on rosetta/package.json
> +    "normalize-css": "^2.3.1",
Why do we downgrade normalize?

2017-06-20 07:12 UTC, lluiscampos commented on rosetta/bower.json
> -{
We also need to remove bower from the documentation (README.md file)

2017-06-20 07:12 UTC, lluiscampos commented on rosetta/Gruntfile.js
>    grunt.registerTask('test', ['browserify:coverage', 'mocha']);
The reason for the test to fail is that they refer to non-existing files in bower_components. We need to modify file rosetta/test/load.js

2017-06-23 18:08 UTC, cristiantrave commented on rosetta/package.json
> +    "normalize-css": "^2.3.1",
Npm says that it is the highest version of which it has references. The message comes up doing npm install command. Performing  tests are normal with this lower version.

2017-06-23 18:16 UTC, cristiantrave commented on rosetta/bower.json
> -{
Now bower references in the README have been deleted

2017-06-23 18:16 UTC, cristiantrave commented on rosetta/Gruntfile.js
>    grunt.registerTask('test', ['browserify:coverage', 'mocha']);
True! Corrected.

2017-06-24 15:34 UTC, lluiscampos approved these changes
Great work :)

2017-06-24 16:17 UTC, merged